FROM golang:1.26-alpine3.24

ENV GO111MODULE=on
ENV GOFLAGS=""
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64

RUN ["apk", "add", "bash", "make", "docker", "curl", "shadow", "git"]
RUN go install go.uber.org/mock/mockgen@v0.6.0
RUN curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o /tmp/kubectl
RUN install -o root -g root -m 0755 /tmp/kubectl /usr/local/bin/kubectl
RUN go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.11.4
RUN export OPERATOR_SDK_DL_URL=https://github.com/operator-framework/operator-sdk/releases/download/v1.37.0 \
    && curl --retry 5 -LO ${OPERATOR_SDK_DL_URL}/operator-sdk_linux_amd64 \
    && echo "20da1fcba9ef70b1e23283ae820a2c3387b529f04ce09cf318597b33f5d59a52  operator-sdk_linux_amd64" | sha256sum -c - \
    && chmod +x operator-sdk_linux_amd64 \
    && install operator-sdk_linux_amd64 /usr/local/bin/operator-sdk


