# permissions for end users to view nodefeaturediscoveries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nodefeaturediscovery-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: node-feature-discovery-operator
    app.kubernetes.io/part-of: node-feature-discovery-operator
    app.kubernetes.io/managed-by: kustomize
  name: nodefeaturediscovery-viewer-role
rules:
- apiGroups:
  - nfd.k8s-sigs.io
  resources:
  - nodefeaturediscoveries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nfd.k8s-sigs.io
  resources:
  - nodefeaturediscoveries/status
  verbs:
  - get
