apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: nfd-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: description of operator
  displayName: node-feature-discovery-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - discovery
  - numa
  - automation
  links:
  - name: Nfd Operator
    url: https://nfd-operator.domain
  maintainers:
  - email: markus.lehtonen@intel.com
    name: Markus
  maturity: alpha
  provider:
    name: k8s-sigs
    url: https://github.com/kubernetes-sigs/node-feature-discovery-operator
  version: 0.0.0
