// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./pkg/apis/nfd/v1alpha1.NodeFeatureDiscovery":       schema_pkg_apis_nfd_v1alpha1_NodeFeatureDiscovery(ref),
		"./pkg/apis/nfd/v1alpha1.NodeFeatureDiscoverySpec":   schema_pkg_apis_nfd_v1alpha1_NodeFeatureDiscoverySpec(ref),
		"./pkg/apis/nfd/v1alpha1.NodeFeatureDiscoveryStatus": schema_pkg_apis_nfd_v1alpha1_NodeFeatureDiscoveryStatus(ref),
	}
}

func schema_pkg_apis_nfd_v1alpha1_NodeFeatureDiscovery(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "NodeFeatureDiscovery is the Schema for the nodefeaturediscoveries API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/nfd/v1alpha1.NodeFeatureDiscoverySpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/nfd/v1alpha1.NodeFeatureDiscoveryStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/nfd/v1alpha1.NodeFeatureDiscoverySpec", "./pkg/apis/nfd/v1alpha1.NodeFeatureDiscoveryStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_nfd_v1alpha1_NodeFeatureDiscoverySpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "NodeFeatureDiscoverySpec defines the desired state of NodeFeatureDiscovery",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_nfd_v1alpha1_NodeFeatureDiscoveryStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "NodeFeatureDiscoveryStatus defines the observed state of NodeFeatureDiscovery",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
