# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Node Feature Discovery Operator
description: >- # this means to ignore newlines until "baseurl:"
  Documentation of Node Feature Discovery Operator - an operator for managing
  detection of hardware features and configuration in a kubernetes cluster.

url: "https://kubernetes-sigs.github.com" # the base hostname & protocol for your site, e.g. http://example.com

repository: kubernetes-sigs/node-feature-discovery-operator

# Build settings
markdown: kramdown
kramdown:
  toc_levels: 1..3

remote_theme: rundocs/jekyll-rtd-theme@v2.0.9

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Document versioning
version: master
display_version_list: true

# Release is the full released version number. Used to make external links to
# point to the correct blobs in the Github repo. This is also the version shown
# in the sidebar (top left corner of the page)
release: master

# Container image which to point to in the documentation
container_image: gcr.io/k8s-staging-nfd/node-feature-discovery-operator:master
# Operand Node Feature Discovery documentation version
operand_version: v0.8
