apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    {{- include "node-feature-discovery-operator.labels" . | nindent 4 }}
  name: {{ include "node-feature-discovery-operator.fullname" . }}-controller-manager-metrics
  namespace: {{ include "node-feature-discovery-operator.namespace" . }}
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: controller-manager
    {{- include "node-feature-discovery-operator.selectorLabels" . | nindent 4 }}
status:
  loadBalancer: {}